# /docker-compose.yml

version: '3.8'

services:
  # 1. The Redis Service
  redis-server:
    image: 'redis:7-alpine' # Use the small 'alpine' version for e2-micro
    container_name: redis-server
    restart: always
    command: redis-server --save 60 1 --loglevel warning # Optional: save db state periodically

  # 2. Your Application Service
  app:
    build: .  # Tells Compose to build the image from the Dockerfile in this directory
    container_name: mentorflow-app
    restart: always
    ports:
      - "80:8080" # Map host port 80 (HTTP) to the container's port 8080
    depends_on:
      - redis-server # Ensures Redis starts before your app does
    environment:
      # This is how your app finds the Redis container.
      # 'redis-server' is the name of the service defined above.
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PORT=8080